language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer update


script:
  - ./vendor/bin/phpunit --version
  - ./vendor/bin/phpunit --no-configuration tests